name: "Setup Spack"
author: "haampie"
description: "Setup Spack"
branding:
  icon: "package"
  color: "blue"
inputs:
  ref:
    description: "Version of Spack (git ref: develop, releases/v0.21, ...)"
    required: false
    default: develop
  buildcache:
    description: "Enable the Github Action build cache"
    required: false
    default: "true"
  color:
    description: "Force color output (sets SPACK_COLOR=always)"
    required: false
    default: "true"
  path:
    description: "Path to install Spack to"
    required: false
    default: "spack"
runs:
  using: "composite"
  steps:
  - name: Checkout Spack
    uses: actions/checkout@v4
    with:
      repository: spack/spack
      path: ${{ inputs.path }}
      ref: ${{ inputs.ref }}

  - name: Spack environment variables
    run: |
      echo "$(realpath ${{ inputs.path }}/bin)" >> "$GITHUB_PATH"
      [ "${{ inputs.color }}" = "true" ] && echo "SPACK_COLOR=always" >> "$GITHUB_ENV"
    shell: sh

  - name: Spack configuration
    run: |
      if [ ${{ inputs.buildcache }} = "true" ]; then
        spack mirror add github-actions-buildcache oci://ghcr.io/spack/github-actions-buildcache
      fi
    shell: sh
