name: "Setup Spack"
author: "haampie"
description: "Set up Spack v1.x with separate core and packages repositories, configurable build cache, and shell integration"
branding:
  icon: "package"
  color: "blue"
inputs:
  spack_ref:
    description: "Version of Spack (git ref: develop, releases/v1.1, ...)"
    required: false
    default: develop
  packages_ref:
    description: "Version of Spack packages (git ref: develop, releases/v1.1, ...)"
    required: false
    default: develop
  buildcache:
    description: "Enable the GitHub Action build cache"
    required: false
    default: "true"
  color:
    description: "Force color output (sets SPACK_COLOR=always)"
    required: false
    default: "true"
  spack_path:
    description: "Path to install Spack to"
    required: false
    default: "spack"
  spack_repository:
    description: "GitHub repository where Spack or its fork lives"
    required: false
    default: "spack/spack"
  packages_repository:
    description: "GitHub repository of the Spack packages repository"
    required: false
    default: "spack/spack-packages"
  packages_path:
    description: "Path to install Spack packages repository"
    required: false
    default: "spack-packages"
runs:
  using: "composite"
  steps:
  - name: Checkout Spack
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    with:
      repository: ${{ inputs.spack_repository }}
      path: ${{ inputs.spack_path }}
      ref: ${{ inputs.spack_ref }}

  - name: Checkout Spack packages
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    with:
      repository: ${{ inputs.packages_repository }}
      path: ${{ inputs.packages_path }}
      ref: ${{ inputs.packages_ref }}

  - name: Spack environment variables
    run: |
      echo "$(realpath "${{ inputs.spack_path }}/bin")" >> "$GITHUB_PATH"
      [ "${{ inputs.color }}" = "true" ] && echo "SPACK_COLOR=always" >> "$GITHUB_ENV"
      echo "SPACK_DISABLE_LOCAL_CONFIG=1" >> "$GITHUB_ENV"
    shell: sh

  - name: Spack configuration
    run: |
      if [ "${{ inputs.buildcache }}" = "true" ]; then
        spack mirror add --unsigned github-actions-buildcache oci://ghcr.io/spack/github-actions-buildcache
      fi
      # Configure separate packages repository
      spack repo set --destination "$(realpath "${{ inputs.packages_path }}")" builtin
    shell: sh

  - name: Create Spack bash shell
    run: |
      cat > "${{ inputs.spack_path }}/bin/spack-bash" <<'EOF'
      #!/bin/bash
      set -e -o pipefail
      SPACK_ROOT="$(realpath "${{ inputs.spack_path }}")" . "$(realpath "${{ inputs.spack_path }}")/share/spack/setup-env.sh"
      . "$1"
      EOF
      chmod +x "${{ inputs.spack_path }}/bin/spack-bash"
    shell: sh

  - name: Create Spack sh shell
    run: |
      cat > "${{ inputs.spack_path }}/bin/spack-sh" <<'EOF'
      #!/bin/sh -e
      SPACK_ROOT="$(realpath "${{ inputs.spack_path }}")" . "$(realpath "${{ inputs.spack_path }}")/share/spack/setup-env.sh"
      . "$1"
      EOF
      chmod +x "${{ inputs.spack_path }}/bin/spack-sh"
    shell: sh
